/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals(4, classUnderTest.sumar(2, 2));
    }
}
