/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.gradle;

public class App {
    public int sumar(int num1, int num2) {
        int suma = num1 + num2;
        return suma;
    }
}
