export const filas = [
    {
        producto:"Manzana",
        cantidad: 5,
        precio: 1.4,
        tienda: "Mercadona",
        notas: "Que sean rojas",
        comprado: true,
        imagen:"https://s1.eestatic.com/2021/09/17/ciencia/nutricion/612699746_208614860_1706x960.jpg",
    },
    {
        producto:"Hummus",
        cantidad: 2,
        precio: 2.2,
        tienda: "Mercadona",
        notas: "El de la caja naranja",
        comprado: true,
        imagen:"https://i.blogs.es/089622/hummus2/450_1000.jpg",
    },
    {
        producto:"Chocolate",
        cantidad: 4,
        precio: 1.1,
        tienda: "Mercadona",
        notas: "El de 80% chocolate",
        comprado: true,
        imagen:"https://i.blogs.es/855ab8/chcoolaate/450_1000.jpg",
    },
    {
        producto:"Cereales",
        cantidad: 1,
        precio: 3.4,
        tienda: "Mercadona",
        notas: "Los de chocolate blanco",
        comprado: false,
        imagen:"https://www.ciudadconalma.com/wp-content/uploads/2021/10/cereales-rellenos-de-leche.jpg",
    },
    {
        producto:"Mayonesa",
        cantidad: 1,
        precio: 1.4,
        tienda: "Mercadona",
        notas: "Comprar la light",
        comprado: true,
        imagen:"https://cdn.businessinsider.es/sites/navi.axelspringer.es/public/media/image/2021/04/clones-mercadona-2300825.jpg?tf=3840x",
    },
    {
        producto:"Patatillas",
        cantidad: 3,
        precio: 1.2,
        tienda: "Mercadona",
        notas: "1 de Jamon y 2 de aceite",
        comprado: true,
        imagen:"https://cdn.businessinsider.es/sites/navi.axelspringer.es/public/media/image/2021/04/clones-mercadona-2300787.jpg?tf=3840x",
    },
]